export const API_BASE_URL = 'https://vue-study.skillbox.cc'
export const API_PRODUCT_CATEGORIES = '/api/productCategories'
export const API_PRODUCTS = '/api/products'
export const API_BASKETS = '/api/baskets'
export const API_BASKETS_PRODUCTS = '/api/baskets/products'
